name: Terraform Deployment

on:
  push:
    branches:
      - main  # Runs automatically on main
  workflow_dispatch:  # Allow manual selection of environment
    inputs:
      environment:
        description: "Choose the environment (dev/prod)"
        required: true
        default: "dev"

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      ENV: ${{ github.event.inputs.environment || 'dev' }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS Credentials
        run: |
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Clean .terraform directory
        run: rm -rf environments/${{ env.ENV }}/.terraform

      - name: List Directory Structure
        run: |
          echo "Listing directory structure for debugging"
          ls -R environments/${{ env.ENV }}

      - name: Initialize Terraform
        run: terraform init
        working-directory: environments/${{ env.ENV }}

      - name: Plan Terraform
        run: terraform plan
        working-directory: environments/${{ env.ENV }}

      - name: Apply Terraform
        run: terraform apply -auto-approve
        working-directory: environments/${{ env.ENV }}

      - name: Capture Terraform Output
        run: |
          terraform output -json > tf_output.json
          VPC_ID=$(jq -r '.vpc_id.value' tf_output.json)
          echo "VPC_ID=$VPC_ID" >> $GITHUB_ENV
        working-directory: environments/${{ env.ENV }}

      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Terraform Deployment - ${{ env.ENV }} ✅"
          body: |
            Terraform has successfully deployed to **${{ env.ENV }}**.
            
            🔹 **VPC ID**: ${{ env.VPC_ID }}
            
            🚀 Deployment completed successfully!
          to: devoperations6@gmail.com
          from: "Terraform Deployment Bot"
          content_type: text/plain
