name: Terraform Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.0"

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Change to the subdirectory containing your Terraform files
      - name: Change to Terraform directory
        working-directory: ./project_casa  # Make sure this path is correct

      - name: Terraform Init
        run: terraform init  # Run init inside the subdirectory
        working-directory: ./project_casa

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: ./project_casa

      - name: Terraform Apply
        if: ${{ github.event_name == 'push' }}
        run: terraform apply -auto-approve tfplan
